Repository sync-without-async/Rehab-FrontEnd, pull requests merged in 2023-11, with the labels that each got.

#36 [Feat/FE] 비대면 진료 예약 목록 페이지에 API를 연결하고 리팩토링을 진행한다.
  src/App.jsx
  src/assets/images/role/role_doctor.png
  src/assets/images/role/role_patient.png
  src/assets/images/role/role_therapist.png
  src/components/Chart/ChartSummary.jsx
  src/components/Input/InputArea.jsx
  src/components/Input/InputAreaContainer.jsx
  src/components/Pagination/Pagination.jsx
  src/components/Reservation/ReservationItem.jsx
  src/components/Reservation/ReservationList.jsx
  src/components/Reservation/ReservationModal.jsx
  src/index.scss
  src/librarys/api/reservation.js
  src/librarys/type.js
  src/pages/Doctor/DoctorUntactReservePage.jsx
  src/reducer/reservation-list.js
  src/reducer/video-list.js
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend, 🛠️ refactoring

#38 [Feat/FE] WebRTC 페이지를 추가한다.
  .env
  src/App.jsx
  src/components/Reservation/ReservationCreateModal.jsx
  src/components/Reservation/ReservationItem.jsx
  src/components/Reservation/ReservationList.jsx
  src/librarys/api/reservation.js
  src/librarys/type.js
  src/librarys/webrtc/rtc-client.js
  src/librarys/webrtc/rtc-recorder.js
  src/librarys/webrtc/rtc-signaling.js
  src/librarys/webrtc/util.js
  src/pages/DevelopPage.jsx
  src/pages/Reservation/ReservationMeetingPage.jsx
  src/reducer/video-list.js
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend

#40 [Feat/FE] 재활치료사 과제 할당 페이지의 API를 예비 연결하고 컴포넌트를 리팩토링한다.
  package-lock.json
  package.json
  src/App.jsx
  src/components/Common/Table.jsx
  src/components/Common/TableItem.jsx
  src/components/Input/InputArea.jsx
  src/components/Input/SearchBar.jsx
  src/components/Pagination/Pagination.jsx
  src/components/TherapistDashBoard/TheraExerciseList.jsx
  src/components/TherapistDashBoard/TheraMakeAssgin.jsx
  src/components/TherapistDashBoard/TheraMakeAssign.jsx
  src/pages/DevelopPage.jsx
  src/pages/Therapist/TheraMakeAssignPage.jsx
  src/reducer/program-assign.js
  src/reducer/reservation-list.js
Labels: 🔨 feature, 💻 frontend, 🛠️ refactoring

#41 [Refactor/FE] 대시보드 페이지의 컴포넌트들을 리팩토링한다.
  src/components/Button/CardButton.jsx
  src/components/Common/BlockContainer.jsx
  src/components/Dashboard/EmployeeHeader.jsx
  src/components/Dashboard/UserHeader.jsx
  src/components/DoctorDashBoard/DoctorDashHeader.jsx
  src/components/Reservation/ReservationMiniList.jsx
  src/components/TherapistDashBoard/TheraMakeAssign.jsx
  src/components/UserDashBoard/UserDashHeader.jsx
  src/librarys/api/video.js
  src/pages/Doctor/DoctorDashBoardPage.jsx
  src/pages/Therapist/TheraDashBoardPage.jsx
  src/pages/User/MyUserPage.jsx
Labels: 🎨 design, 🔨 feature, 💻 frontend

#42 [Refactor/FE] 회원가입 페이지를 리팩토링한다.
  src/components/Accounts/SignupComponents.jsx
  src/components/Button/Button.jsx
  src/components/Common/Callout.jsx
  src/components/Common/Table.jsx
  src/components/Dropdown/DropdownFilter.jsx
  src/components/Input/InputImage.jsx
  src/components/Reservation/ReservationCreateModal.jsx
  src/components/TherapistDashBoard/TheraExerciseList.jsx
  src/components/TherapistDashBoard/TheraMakeAssign.jsx
  src/components/TherapistDashBoard/TheraPatientList.jsx
  src/components/UserDashBoard/UserAssignList.jsx
  src/librarys/api/login.js
  src/librarys/api/video.js
  src/pages/SignupPage.jsx
Labels: 💻 frontend, 🛠️ refactoring

#43 [Refactor/FE] 로그인 Redux API를 변경하고 대시보드 페이지를 단일화한다.
  src/App.jsx
  src/components/Accounts/LoginComponents.jsx
  src/components/Common/Modal.jsx
  src/components/Dashboard/EmployeeHeader.jsx
  src/components/Dashboard/QuickLink.jsx
  src/components/Dashboard/UserHeader.jsx
  src/components/Input/InputImage.jsx
  src/components/Reservation/ReservationList.jsx
  src/components/Reservation/ReservationMiniList.jsx
  src/components/TherapistDashBoard/TheraExerciseList.jsx
  src/components/UntactReserve/UntactReserveList.jsx
  src/librarys/api/video.js
  src/librarys/dummy-api.js
  src/pages/DashboardPage.jsx
  src/pages/Doctor/DoctorDashBoardPage.jsx
  src/pages/Therapist/TheraDashBoardPage.jsx
  src/pages/Therapist/TheraDetailPage.jsx
  src/pages/User/MyUserPage.jsx
  src/redux/userSlice.js
Labels: 🔨 feature, 💻 frontend, 🛠️ refactoring

#44 [Refactor/FE] 환자 목록 페이지를 단일화하고 리팩토링한다.
  src/App.jsx
  src/components/Chart/PatientList.jsx
  src/components/Dashboard/QuickLink.jsx
  src/components/DoctorDashBoard/DoctorPatientList.jsx
  src/components/Reservation/ReservationCreateModal.jsx
  src/components/Reservation/ReservationItem.jsx
  src/components/Reservation/ReservationList.jsx
  src/components/Reservation/ReservationMiniItem.jsx
  src/components/Reservation/ReservationMiniList.jsx
  src/components/TherapistDashBoard/TheraExerciseAdd.jsx
  src/components/TherapistDashBoard/TheraMakeAssign.jsx
  src/components/TherapistDashBoard/TheraPatientList.jsx
  src/pages/DevelopPage.jsx
  src/pages/Doctor/DoctorChartPage.jsx
  src/pages/Doctor/DoctorDetailPage.jsx
  src/pages/Doctor/DoctorPatientListPage.jsx
  src/pages/PatientListPage.jsx
  src/pages/Reservation/ReservationCreatePage.jsx
  src/pages/Reservation/ReservationListPage.jsx
  src/pages/Reservation/ReservationMeetingPage.jsx
  src/pages/Therapist/TheraDetailPage.jsx
  src/pages/Therapist/TheraExerciseAddPage.jsx
  src/pages/Therapist/TheraExerciseListPage.jsx
  src/pages/Therapist/TheraMakeAssignPage.jsx
  src/pages/Therapist/TheraPatientListPage.jsx
  src/reducer/chart-assign.js
  src/reducer/chart.js
  src/reducer/meeting-create.js
  src/reducer/meeting-list.js
Labels: 💻 frontend, 🛠️ refactoring

#45 [Refactor/FE] Table 컴포넌트에서 DnD 요소를 분리한다.
  src/components/Chart/PatientList.jsx
  src/components/Common/DnDItem.jsx
  src/components/Common/DnDList.jsx
  src/components/Common/Table.jsx
  src/components/Common/TableItem.jsx
  src/components/TherapistDashBoard/TheraExerciseAdd.jsx
  src/components/TherapistDashBoard/TheraMakeAssign.jsx
  src/components/UserDashBoard/UserAssignList.jsx
  src/librarys/api/video.js
Labels: 🔨 feature, 💻 frontend, 🛠️ refactoring

#46 [Feat/FE] 프로그램 수강 페이지를 추가하고 비대면 진료 페이지의 디자인을 수정한다.
  src/App.jsx
  src/components/Accounts/LoginComponents.jsx
  src/components/Accounts/SignupComponents.jsx
  src/components/Common/Header.jsx
  src/components/Common/Modal.jsx
  src/components/Common/TableItem.jsx
  src/components/DoctorDashBoard/DoctorChart.jsx
  src/components/Dropdown/Dropdown.jsx
  src/components/Reservation/ReservationItem.jsx
  src/components/player/BorderBox.jsx
  src/components/player/ControllerSection.jsx
  src/components/player/Countdown.jsx
  src/components/player/GuideSection.jsx
  src/components/player/ResultModal.jsx
  src/components/player/StartupModal.jsx
  src/components/player/Subtitle.jsx
  src/librarys/api/program.js
  src/librarys/player.js
  src/pages/DevelopPage.jsx
  src/pages/ProgramPage.jsx
  src/pages/Reservation/ReservationMeetingPage.jsx
  src/reducer/player.js
  src/redux/modalSlice.js
  src/redux/userSlice.js
Labels: 🔨 feature, 💻 frontend, 🛠️ refactoring

#47 [Feat/FE] 로그인 권한에 따라서 접근 가능한 페이지를 다르게 설정한다.
  src/App.jsx
  src/components/Accounts/LoginComponents.jsx
  src/components/Common/DnDItem.jsx
  src/components/Common/Modal.jsx
  src/components/Route/AuthorizedRoute.jsx
  src/components/TherapistDashBoard/TheraSeveralExercise.jsx
  src/components/player/StartupModal.jsx
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend

#48 [Feat/FE] 회원가입 API 연결 구현
  .env
  package-lock.json
  package.json
  src/components/Accounts/SignupComponents.jsx
  src/components/Button/RoleButton.jsx
  src/components/Input/InputImage.jsx
  src/components/Input/InputText.jsx
  src/components/Input/InputTextContainer.jsx
  src/librarys/api/signup.js
Labels: 🔨 feature, 💻 frontend

#50 [Feat/FE] Video API와 Reservation API를 구현하고 연결한다.
  src/components/Reservation/ReservationCreateModal.jsx
  src/components/Reservation/ReservationInfoModal.jsx
  src/components/TherapistDashBoard/TheraExerciseAdd.jsx
  src/components/TherapistDashBoard/TheraExerciseList.jsx
  src/components/TherapistDashBoard/TheraMakeAssign.jsx
  src/librarys/api/axios.js
  src/librarys/api/reservation.js
  src/librarys/api/video.js
  src/reducer/chart-assign.js
  src/reducer/video-list.js
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend, 🛠️ refactoring

#51 [Feat/FE] 백엔드에서 새롭게 구현한 API들을 구현한다.
  src/components/TherapistDashBoard/TheraVideoUploader.jsx
  src/librarys/api/ai.js
  src/librarys/api/chart.js
  src/librarys/api/program.js
  src/librarys/api/user.js
  src/librarys/player.js
Labels: 🔨 feature, 💻 frontend

#52 [Feat/FE] 전문의의 환자 차트 등록/ 재활치료사 목록 조회 API 연결을 구현한다.
  src/components/DoctorDashBoard/DoctorChart.jsx
  src/components/Input/DateSelect.jsx
  src/components/Input/InputTextLong.jsx
  src/librarys/api/chart.js
Labels: 🔨 feature, 💻 frontend

#53 [Refactor/FE] 회원가입 페이지를 리팩토링한다.
  src/components/Accounts/SignupComponents.jsx
  src/components/Common/DnDList.jsx
  src/components/Input/InputArea.jsx
  src/components/Input/InputImage.jsx
  src/components/Input/InputText.jsx
  src/components/Reservation/ReservationSelect.jsx
  src/components/TherapistDashBoard/TheraMakeAssign.jsx
  src/components/UserDashBoard/UserSelectCard.jsx
  src/librarys/api/image.js
  src/librarys/api/user.js
  src/librarys/util.js
  src/reducer/user-register.js
Labels: 🔨 feature, 💻 frontend, 🛠️ refactoring

#54 [Feat/FE] 전문의의 진료 기록 추가 및 환자 진료 기록 조회 API 연결 구현
  src/components/DoctorDashBoard/DoctorChartWrite.jsx
  src/components/DoctorDashBoard/DoctorFaceRecord.jsx
  src/components/Input/InputTextLong.jsx
  src/librarys/api/chart.js
Labels: 🔨 feature, 💻 frontend

#56 [Feat/FE] 전반적인 API 연결을 진행한다. ( 환자 상세 차트의 모든 것)
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/✅-feature.md
  .github/ISSUE_TEMPLATE/🐛-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/components/Button/RoleButton.jsx
  src/components/Chart/ChartSummary.jsx
  src/components/Common/UserComponents.jsx
  src/components/DoctorDashBoard/CircleChart.jsx
  src/components/DoctorDashBoard/DoctorChartWrite.jsx
  src/components/DoctorDashBoard/DoctorCheckDetail.jsx
  src/components/DoctorDashBoard/DoctorDetailChart.jsx
  src/components/DoctorDashBoard/DoctorDetailHeader.jsx
  src/components/DoctorDashBoard/DoctorFaceRecord.jsx
  src/components/DoctorDashBoard/DoctorUntactRecord.jsx
  src/components/Input/DateSelect.jsx
  src/components/Input/InputDText.jsx
  src/components/Input/InputTextContainer.jsx
  src/components/Input/InputTextLong.jsx
  src/components/TherapistDashBoard/TheraCheckDetail.jsx
  src/components/TherapistDashBoard/TherafromDoctor.jsx
  src/components/UserDashBoard/UserUntactList.jsx
  src/librarys/api/chart.js
  src/librarys/context.js
  src/librarys/webrtc/rtc-signaling.js
  src/librarys/webrtc/util.js
  src/pages/Doctor/DoctorDetailPage.jsx
  src/reducer/player.js
  vercel.json
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend

#58 [Feat/FE] 차트 상세 페이지 API를 1차 연결한다.
  package-lock.json
  src/components/Chart/PatientList.jsx
  src/components/Common/Table.jsx
  src/components/Common/TableItem.jsx
  src/components/Dashboard/EmployeeHeader.jsx
  src/components/DoctorDashBoard/CircleChart.jsx
  src/components/DoctorDashBoard/DoctorChart.jsx
  src/components/DoctorDashBoard/DoctorCheckHW.jsx
  src/components/DoctorDashBoard/DoctorDetailChart.jsx
  src/components/DoctorDashBoard/DoctorDetailHeader.jsx
  src/components/DoctorDashBoard/DoctorFaceRecord.jsx
  src/components/Reservation/ReservationItem.jsx
  src/components/Reservation/ReservationList.jsx
  src/components/Reservation/ReservationMiniItem.jsx
  src/components/Reservation/ReservationMiniList.jsx
  src/librarys/api/ai.js
  src/librarys/api/chart.js
  src/librarys/api/reservation.js
  src/librarys/api/user.js
  src/librarys/type.js
  src/librarys/util.js
  src/librarys/webrtc/rtc-client.js
  src/pages/Doctor/DoctorDetailPage.jsx
  src/pages/Reservation/ReservationMeetingPage.jsx
  src/reducer/chart-detail.js
  src/reducer/chart-list.js
  src/redux/userSlice.js
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend, 🛠️ refactoring

#59 [Feat/FE] 프로젝트의 스타일 요소들을 추가로 구현하다.
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/MainLogo.png
  src/components/Accounts/LoginComponents.jsx
  src/components/Accounts/SignupComponents.jsx
  src/components/Common/Header.jsx
  src/components/Reservation/ReservationInfoModal.jsx
  src/components/TherapistDashBoard/TheraExerciseAdd.jsx
  src/components/TherapistDashBoard/TheraMakeAssign.jsx
  src/pages/ProgramPage.jsx
Labels: 🎨 design, 🔨 feature

#60 [Feat/FE] API들을 최종 연결하고 일부 API의 변동 사항을 적용한다.
  package-lock.json
  package.json
  src/App.jsx
  src/components/Chart/PatientList.jsx
  src/components/Common/TitleText.jsx
  src/components/Dashboard/UserHeader.jsx
  src/components/DoctorDashBoard/DoctorChart.jsx
  src/components/DoctorDashBoard/DoctorCheckHW.jsx
  src/components/DoctorDashBoard/DoctorRecord.jsx
  src/components/Input/InputArea.jsx
  src/components/Input/InputText.jsx
  src/components/Reservation/ReservationList.jsx
  src/components/Reservation/ReservationMiniList.jsx
  src/components/TherapistDashBoard/TheraExerciseList.jsx
  src/components/UserDashBoard/UserAssignList.jsx
  src/librarys/api/chart.js
  src/librarys/api/program.js
  src/librarys/api/reservation.js
  src/pages/Doctor/DoctorDetailPage.jsx
  src/pages/Reservation/ReservationMeetingPage.jsx
  src/pages/Therapist/TheraDetailPage.jsx
  src/reducer/chart-create.js
  src/reducer/chart-detail.js
  vite.config.js
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend, 🛠️ refactoring

#61 [Feat/FE] 로그아웃, 404 페이지, WebRTC 결과 modal, 진료기록 modal, 비밀번호 form 기능을 추가한다.
  src/App.jsx
  src/components/Accounts/LoginComponents.jsx
  src/components/Accounts/SignupComponents.jsx
  src/components/Common/Header.jsx
  src/components/Common/TitleText.jsx
  src/components/DoctorDashBoard/DoctorCreateModal.jsx
  src/components/DoctorDashBoard/DoctorFaceRecord.jsx
  src/components/DoctorDashBoard/DoctorRecord.jsx
  src/components/DoctorDashBoard/DoctorUntactRecord.jsx
  src/components/Input/InputText.jsx
  src/components/Input/InputTextContainer.jsx
  src/components/Meeting/MeetingResultModal.jsx
  src/components/Meeting/MeetingStartupModal.jsx
  src/components/Reservation/ReservationInfoModal.jsx
  src/components/Route/AuthorizedRoute.jsx
  src/components/TherapistDashBoard/TheraExerciseAdd.jsx
  src/components/TherapistDashBoard/TheraMakeAssign.jsx
  src/components/TherapistDashBoard/TheraVideoUploader.jsx
  src/librarys/api/chart.js
  src/main.jsx
  src/pages/Doctor/DoctorChartPage.jsx
  src/pages/Doctor/DoctorDetailPage.jsx
  src/pages/LogoutPage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/ProgramPage.jsx
  src/pages/Reservation/ReservationMeetingPage.jsx
  src/reducer/meeting-room.js
  src/redux/userSlice.js
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend, 🛠️ refactoring

#62 [Feat/FE] 최종 API 연결을 완료하고 테스트 진행
  src/App.jsx
  src/assets/images/user/default.png
  src/components/Chart/PatientList.jsx
  src/components/Common/Header.jsx
  src/components/Dashboard/UserHeader.jsx
  src/components/DoctorDashBoard/DoctorDetailChart.jsx
  src/components/Reservation/ReservationCreateModal.jsx
  src/components/Reservation/ReservationInfoModal.jsx
  src/components/Reservation/ReservationItem.jsx
  src/components/Reservation/ReservationList.jsx
  src/components/Reservation/ReservationSelect.jsx
  src/components/TherapistDashBoard/TheraMakeAssign.jsx
  src/components/UserDashBoard/UserAssignList.jsx
  src/components/player/BorderBox.jsx
  src/components/player/ControllerSection.jsx
  src/components/player/Countdown.jsx
  src/components/player/GuideSection.jsx
  src/components/player/ResultModal.jsx
  src/components/player/Subtitle.jsx
  src/librarys/api/chart.js
  src/librarys/api/program.js
  src/librarys/api/reservation.js
  src/librarys/api/user.js
  src/librarys/player.js
  src/pages/ConvertChartPage.jsx
  src/pages/ProgramPage.jsx
  src/reducer/player.js
  src/redux/userSlice.js
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend, 🛠️ refactoring, 📱 ui

#63 [Fix/FE] 비어있는 AI 요약이 표시되는 문제 수정
  src/components/DoctorDashBoard/DoctorChart.jsx
  src/pages/Doctor/DoctorDetailPage.jsx
Labels: 🔧 fix_issue, 💻 frontend

#68 [Chore/FE] 버그 수정 및 디테일 추
  .env
  src/App.jsx
  src/components/Accounts/LoginComponents.jsx
  src/components/Accounts/SignupComponents.jsx
  src/components/Chart/PatientList.jsx
  src/components/Common/Empty.jsx
  src/components/Common/Table.jsx
  src/components/DoctorDashBoard/DoctorRecord.jsx
  src/components/Input/DateSelect.jsx
  src/components/Input/InputAreaContainer.jsx
  src/components/Input/InputText.jsx
  src/components/Input/InputTextContainer.jsx
  src/components/Reservation/ReservationCreateModal.jsx
  src/components/Reservation/ReservationInfoModal.jsx
  src/components/Reservation/ReservationItem.jsx
  src/components/Reservation/ReservationList.jsx
  src/components/Reservation/ReservationMiniItem.jsx
  src/components/Reservation/ReservationMiniList.jsx
  src/components/TherapistDashBoard/TheraExerciseList.jsx
  src/components/UserDashBoard/UserAssignList.jsx
  src/librarys/api/chart.js
  src/librarys/api/reservation.js
  src/librarys/webrtc/rtc-client.js
  src/pages/Doctor/DoctorDetailPage.jsx
  src/pages/Reservation/ReservationMeetingPage.jsx
  src/redux/userSlice.js
Labels: 🔧 fix_issue, 💻 frontend, 🛠️ refactoring
